=== Bastion-RND/school-lab/specifications/schema/multisensor.schema.json
{
  "$id": "multisensor.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "School Laboratory Configuration",
  "description": "School Laboratory multisensor (lab) config",
  "$definitions": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "title": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 1,
      "maxLength": 64
    },
    "description": {
      "type": "string",
      "maxLength": 256
    },
    "moduleName": {
      "type": "string",
      "maxLength": 32
    }
  },
  "type": "object",
  "properties": {
    "disabled": {
      "type": "boolean",
      "default": false
    },
    "uuid": {
      "$ref": "#/$definitions/uuid"
    },
    "title": {
      "$ref": "#/$definitions/title"
    },
    "description": {
      "$ref": "#/$definitions/description"
    },
    "moduleName": {
      "$ref": "#/$definitions/moduleName"
    },
    "advName": {
      "type": "string",
      "maxLength": 16
    },
    "sensors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "$ref": "#/$definitions/title"
          },
          "description": {
            "$ref": "#/$definitions/description"
          },
          "uuid": {
            "$ref": "#/$definitions/uuid"
          }
        },
        "required": [
          "uuid"
        ]
      }
    }
  },
  "required": [
    "uuid",
    "sensors",
    "advName",
    "moduleName"
  ]
}

=== Bastion-RND/school-lab/specifications/51C0.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "000051C0-0000-1000-8000-00805f9b34fb",
  "title": "ОПС",
  "advName": "OPS #",
  "moduleName": "lib.laboratories.OPS",
  "sensors": [
    {
      "description": "Температура воздуха",
      "uuid": "ba575002-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Относительная влажность воздуха",
      "uuid": "ba575003-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Уровень освещенности",
      "uuid": "ba575004-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/5100.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "description": "Экспериментальная лаборатория (для тестов)",
  "uuid": "00005100-0000-1000-8000-00805f9b34fb",
  "disabled": true,
  "title": "Dummy lab",
  "advName": "Dummy #",
  "moduleName": "DUMMY",
  "sensors": [
    {
      "description": "Dummy sensor 1",
      "uuid": "f001da7a-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Dummy sensor 2",
      "uuid": "f002da7a-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Dummy sensor 3",
      "uuid": "f003da7a-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/51C5.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "000051c5-0000-1000-8000-00805f9b34fb",
  "title": "Измеритель уровня шума",
  "advName": "NOISE #",
  "moduleName": "NOISE",
  "sensors": [
 {
   "description": "Уровень шума",
   "uuid": "ba575014-eca0-11ec-8ea0-1337ac062022",
   "sound": {
     "sensorType": 0,
     "soundNumber": 120
   }
 }
  ]
}

=== Bastion-RND/school-lab/specifications/5104.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "00005104-0000-1000-8000-00805f9b34fb",
  "title": "Физиология",
  "advName": "Physiology #",
  "moduleName": "PHYSIOLOGY",
  "sensors": [
    {
      "description": "Уровень освещенности",
      "uuid": "ba575004-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура, датчик NTC",
      "uuid": "ba575015-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Ускорение по осям",
      "uuid": "ba57500b-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Частота сердечных сокращений",
      "uuid": "ba575013-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Электрокардиограф",
      "uuid": "ba575012-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Частота дыхания",
      "uuid": "ba57501b-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Артериальное давление",
      "uuid": "ba57501c-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Динамометр",
      "uuid": "ba57500f-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/51C3.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "000051c3-0000-1000-8000-00805f9b34fb",
  "title": "Измеритель углекислого газа",
  "advName": "CO2VOC #",
  "moduleName": "CO2VOC",
  "sensors": [
    {
      "description": "Двуокись углерода",
      "uuid": "ba575011-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 117
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/51C2.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "000051c2-0000-1000-8000-00805f9b34fb",
  "title": "Измеритель расстояния",
  "advName": "Distance #",
  "moduleName": "lib.laboratories.Distance",
  "sensors": [
    {
      "description": "Измеритель расстояния",
      "uuid": "ba575019-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/5101.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "00005101-0000-1000-8000-00805f9b34fb",
  "title": "Физика",
  "advName": "Physics #",
  "moduleName": "PHYSICS",
  "sensors": [
    {
      "description": "Напряжение",
      "uuid": "ba57500A-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 110
      }
    },
    {
      "description": "Сила тока",
      "uuid": "ba575009-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 109
      }
    },
    {
      "description": "Гальванометр",
      "uuid": "ba575021-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 133
      }
    },
    {
      "description": "Индукция магнитного поля",
      "uuid": "ba575007-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 107
      }
    },
    {
      "description": "Температура (ЩУП)",
      "uuid": "ba575001-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 101
      }
    },
    {
      "description": "Давление воздуха",
      "uuid": "ba575006-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 106
      }
    },
    {
      "description": "Ускорение по осям",
      "uuid": "ba57500B-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 111
      }
    },
    {
      "description": "Напряжение и ток",
      "uuid": "ba575C02-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 202
      }
    },
    {
      "description": "Сила тока и температура (ЩУП)",
      "uuid": "ba575C03-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 203
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/51C1.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "000051c1-0000-1000-8000-00805f9b34fb",
  "title": "Счетчик капель",
  "advName": "DROPS #",
  "moduleName": "DROPS",
  "sensors": [
    {
      "description": "Устройство подсчета капель на штатив",
      "uuid": "ba57501a-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 126
      }
    }
  ]
}
