=== Bastion-RND/school-lab/specifications/schema/multisensor.schema.json
{
  "$id": "multisensor.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "School Laboratory Configuration",
  "description": "School Laboratory multisensor (lab) config",
  "$definitions": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "title": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 1,
      "maxLength": 64
    },
    "description": {
      "type": "string",
      "maxLength": 256
    },
    "moduleName": {
      "type": "string",
      "maxLength": 32
    }
  },
  "type": "object",
  "properties": {
    "disabled": {
      "type": "boolean",
      "default": false
    },
    "uuid": {
      "$ref": "#/$definitions/uuid"
    },
    "title": {
      "$ref": "#/$definitions/title"
    },
    "description": {
      "$ref": "#/$definitions/description"
    },
    "moduleName": {
      "$ref": "#/$definitions/moduleName"
    },
    "advName": {
      "type": "string",
      "maxLength": 16
    },
    "sensors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "$ref": "#/$definitions/title"
          },
          "description": {
            "$ref": "#/$definitions/description"
          },
          "uuid": {
            "$ref": "#/$definitions/uuid"
          }
        },
        "required": [
          "uuid"
        ]
      }
    }
  },
  "required": [
    "uuid",
    "sensors",
    "advName",
    "moduleName"
  ]
}

=== Bastion-RND/school-lab/specifications/5103.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "00005103-0000-1000-8000-00805f9b34fb",
  "title": "Биология",
  "advName": "Biology #",
  "moduleName": "lib.laboratories.Chemistry",
  "sensors": [
    {
      "description": "Водородный показатель (pH)",
      "uuid": "ba575008-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура (ЩУП)",
      "uuid": "ba575001-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура воздуха",
      "uuid": "ba575002-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Относительная влажность воздуха",
      "uuid": "ba575003-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Уровень освещенности",
      "uuid": "ba575004-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Водородный показатель (pH) и температура (ЩУП)",
      "uuid": "ba575C04-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура и относительная влажность воздуха",
      "uuid": "ba575C01-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/5102.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "00005102-0000-1000-8000-00805f9b34fb",
  "title": "Химия",
  "advName": "Chemistry #",
  "moduleName": "CHEMISTRY",
  "sensors": [
    {
      "description": "Водородный показатель (pH)",
      "uuid": "ba575008-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Окислительно-восстановительный потенциал (Eh)",
      "uuid": "ba575023-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Оптическая плотность среды",
      "uuid": "ba57500C-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура (ЩУП)",
      "uuid": "ba575001-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Электрическая проводимость",
      "uuid": "ba575005-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Концентрация ионов",
      "uuid": "ba575024-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Концентрация ионов",
      "uuid": "ba575024-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "PH – показатель среды и температура (ЩУП)",
      "uuid": "ba575C04-eca0-11ec-8ea0-1337ac062022"
    },
    {
      "description": "Температура (ЩУП) и электрическая проводимость",
      "uuid": "ba575C05-eca0-11ec-8ea0-1337ac062022"
    }
  ]
}

=== Bastion-RND/school-lab/specifications/5105.spec.json
{
  "$schema": "schema/multisensor.schema.json",
  "uuid": "00005105-0000-1000-8000-00805f9b34fb",
  "title": "Экология",
  "advName": "Ecology #",
  "moduleName": "ECOLOGY",
  "sensors": [
    {
      "description": "Температура воздуха",
      "uuid": "ba575002-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 102
      }
    },
    {
      "description": "Относительная влажность воздуха",
      "uuid": "ba575003-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 103
      }
    },
    {
      "description": "Точка росы",
      "uuid": "ba57501f-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 131
      }
    },
    {
      "description": "Температура, датчик NTC",
      "uuid": "ba575015-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 121
      }
    },
    {
      "description": "Водородный показатель (pH)",
      "uuid": "ba575008-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 108
      }
    },
    {
      "description": "Электрическая проводимость",
      "uuid": "ba575005-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 105
      }
    },
    {
      "description": "Концентрация ионов",
      "uuid": "ba575024-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 136
      }
    },
    {
      "description": "Уровень освещенности",
      "uuid": "ba575004-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 104
      }
    },    
    {
      "description": "Мутность раствора",
      "uuid": "ba57501d-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 129
      }
    },
    {
      "description": "Оптическая плотность среды",
      "uuid": "ba57500c-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 112
      }
    },
    {
      "description": "Влажность почвы",
      "uuid": "ba575016-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 122
      }
    },
    {
      "description": "Концентрация углекислого газа",
      "uuid": "ba575011-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 117
      }
    },
    {
      "description": "Концентрация ЛОВ",
      "uuid": "ba575020-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 132
      }
    },
    {
      "description": "Концентрация нитрат-ионов",
      "uuid": "ba575017-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 123
      }
    },
    {
      "description": "Концентрация хлорид-ионов",
      "uuid": "ba575018-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 124
      }
    },
    {
      "description": "Уровень шума",
      "uuid": "ba575014-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 0,
        "soundNumber": 120
      }
    },
    {
      "description": "Температура, влажность, точка росы",
      "uuid": "ba575c07-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 206
      }
    },
    {
      "description": "Концентрация CO2, ЛОВ",
      "uuid": "ba575c08-eca0-11ec-8ea0-1337ac062022",
      "sound": {
        "sensorType": 1,
        "soundNumber": 207
      }
    }
  ]
}
