=== Bastion-RND/school-lab/specifications/schema/sensor.schema.json
{
  "$id": "specification.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$definitions": {
    "title": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 1,
      "maxLength": 64
    },
    "rangeListItem": {
      "description": "Range specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "factor": {
          "type": "string",
          "enum": [
            "NORMAL",
            "PICO",
            "NANO",
            "MICRO",
            "MILLI",
            "KILO",
            "MEGA",
            "GIGA",
            "TERA"
          ],
          "default": "NORMAL"
        },
        "precision": {
          "type": "integer",
          "default": 2
        },
        "calibrationPointsMin": {
          "type": "integer",
          "default": 2
        }
      },
      "required": [
        "min",
        "max",
        "factor",
        "precision",
        "calibrationPointsMin"
      ]
    },
    "yAxisItemRange": {
      "description": "YAxis Ranges Specifications",
      "type": "object",
      "properties": {
        "list": {
          "type": "array",
          "items": {
            "$ref": "#/$definitions/rangeListItem"
          },
          "minItems": 1
        },
        "defaultIndex": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        }
      },
      "required": [
        "list",
        "defaultIndex"
      ]
    },
    "yAxisItem": {
      "description": "Single YAxis Specifications",
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "unit": {
          "type": "string",
          "maxLength": 10
        },
        "range": {
          "$ref": "#/$definitions/yAxisItemRange"
        },
        "required": [
          "title",
          "unit",
          "range"
        ]
      }
    },
    "valueItem": {
      "description": "Single Value Specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "yAxisIndex": {
          "type": "integer",
          "default": 0
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "chart",
              "chart2",
              "chart3",
              "chart4",
              "gauge",
              "reference",
              "current",
              "measurements",
              "minmax",
              "bloodPressure",
              "pulse"
            ]
          },
          "minItems": 1,
          "uniqueItems": true,
          "default": [
            "chart",
            "gauge",
            "current",
            "measurements"
          ]
        },
        "errors": {
          "description": "Error Codes with default texts",
          "type": "object"
        }
      },
      "required": [
        "title",
        "options",
        "yAxisIndex",
        "errors"
      ]
    }
  },
  "title": "Sensor specifications",
  "description": "School Laboratory sensor specifications",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "description": {
      "type": "string",
      "maxLength": 64
    },
    "info": {
      "description": "Sensor common information",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "sortOrder": {
          "type": "integer",
          "minimum": -1,
          "default": -1
        }
      },
      "required": [
        "title",
        "sortOrder"
      ]
    },
    "yAxis": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/yAxisItem"
      },
      "minItems": 1
    },
    "stage": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "value": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/valueItem"
      },
      "minItems": 1
    }
  },
  "required": [
    "uuid",
    "info",
    "yAxis",
    "value",
    "description"
  ]
}

=== Bastion-RND/school-lab/specifications/ba575010.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575010-eca0-11ec-8ea0-1337ac062022",
  "description": "Артериальное давление",
  "info": {
    "title": "Артериальное давление",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "Па",
      "title": "Давление",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 40000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57500c.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57500c-eca0-11ec-8ea0-1337ac062022",
  "description": "Оптическая плотность",
  "info": {
    "title": "Оптическая плотность среды",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " D",
      "title": "Экстинкция",
      "range": {
        "list": [
          {
            "title": "λ 470",
            "min": 0,
            "max": 2,
            "precision": 3,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "title": "λ 525",
            "min": 0,
            "max": 2,
            "precision": 3,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "title": "λ 630",
            "min": 0,
            "max": 2,
            "precision": 3,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 1
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "current",
        "reference",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575011.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575011-eca0-11ec-8ea0-1337ac062022",
  "description": "Двуокись углерода",
  "info": {
    "title": "Концентрация CO2",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "ppm",
      "title": "Двуокись углерода",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 5000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": 0.0,
            "max": 10000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": 0.0,
            "max": 50000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575c02.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575c02-eca0-11ec-8ea0-1337ac062022",
  "description": "Напряжение + Сила тока",
  "info": {
    "title": "Напряжение и ток",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " В",
      "title": "Напряжение",
      "range": {
        "list": [
          {
            "min": -2.0,
            "max": 2.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": -5.0,
            "max": 5.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "min": -10.0,
            "max": 10.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "min": -15.0,
            "max": 15.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "min": -20.0,
            "max": 20.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          }
        ],
        "defaultIndex": 0
      }
    },
    {
      "unit": " А",
      "title": "Сила тока",
      "range": {
        "list": [
          {
            "min": -1.0,
            "max": 1.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": -5.0,
            "max": 5.0,
            "precision": 3,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    },
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 1,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57500b.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57500b-eca0-11ec-8ea0-1337ac062022",
  "description": "Ускорение (акселерометр)",
  "info": {
    "title": "Ускорение по осям",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " g",
      "title": "Ускорение",
      "range": {
        "list": [
          {
            "min": -2.0,
            "max": 2.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          },
          {
            "min": -4.0,
            "max": 4.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": -8.0,
            "max": 8.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": -16.0,
            "max": 16.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": "Ось X",
      "options": [
        "chart",
        "gauge",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    },
    {
      "title": "Ось Y",
      "options": [
        "chart",
        "gauge",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    },
    {
      "title": "Ось Z",
      "options": [
        "chart",
        "gauge",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57500d.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57500d-eca0-11ec-8ea0-1337ac062022",
  "description": "Температура воздуха",
  "info": {
    "title": "Температура воздуха",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "°C",
      "title": "Температура",
      "range": {
        "list": [
          {
            "min": -40.0,
            "max": 80.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575026.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575026-eca0-11ec-8ea0-1337ac062022",
  "description": "Концентрация кислорода",
  "info": {
    "title": "Концентрация O2",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "%",
      "title": "Кислород",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 25.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57500f.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57500f-eca0-11ec-8ea0-1337ac062022",
  "description": "Тензодатчик",
  "info": {
    "title": "Динамометр",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "кг",
      "title": "Вес",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 50.0,
            "precision": 3,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}
