=== Bastion-RND/school-lab/specifications/schema/sensor.schema.json
{
  "$id": "specification.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$definitions": {
    "title": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 1,
      "maxLength": 64
    },
    "rangeListItem": {
      "description": "Range specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "factor": {
          "type": "string",
          "enum": [
            "NORMAL",
            "PICO",
            "NANO",
            "MICRO",
            "MILLI",
            "KILO",
            "MEGA",
            "GIGA",
            "TERA"
          ],
          "default": "NORMAL"
        },
        "precision": {
          "type": "integer",
          "default": 2
        },
        "calibrationPointsMin": {
          "type": "integer",
          "default": 2
        }
      },
      "required": [
        "min",
        "max",
        "factor",
        "precision",
        "calibrationPointsMin"
      ]
    },
    "yAxisItemRange": {
      "description": "YAxis Ranges Specifications",
      "type": "object",
      "properties": {
        "list": {
          "type": "array",
          "items": {
            "$ref": "#/$definitions/rangeListItem"
          },
          "minItems": 1
        },
        "defaultIndex": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        }
      },
      "required": [
        "list",
        "defaultIndex"
      ]
    },
    "yAxisItem": {
      "description": "Single YAxis Specifications",
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "unit": {
          "type": "string",
          "maxLength": 10
        },
        "range": {
          "$ref": "#/$definitions/yAxisItemRange"
        },
        "required": [
          "title",
          "unit",
          "range"
        ]
      }
    },
    "valueItem": {
      "description": "Single Value Specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "yAxisIndex": {
          "type": "integer",
          "default": 0
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "chart",
              "chart2",
              "chart3",
              "chart4",
              "gauge",
              "reference",
              "current",
              "measurements",
              "minmax",
              "bloodPressure",
              "pulse"
            ]
          },
          "minItems": 1,
          "uniqueItems": true,
          "default": [
            "chart",
            "gauge",
            "current",
            "measurements"
          ]
        },
        "errors": {
          "description": "Error Codes with default texts",
          "type": "object"
        }
      },
      "required": [
        "title",
        "options",
        "yAxisIndex",
        "errors"
      ]
    }
  },
  "title": "Sensor specifications",
  "description": "School Laboratory sensor specifications",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "description": {
      "type": "string",
      "maxLength": 64
    },
    "info": {
      "description": "Sensor common information",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "sortOrder": {
          "type": "integer",
          "minimum": -1,
          "default": -1
        }
      },
      "required": [
        "title",
        "sortOrder"
      ]
    },
    "yAxis": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/yAxisItem"
      },
      "minItems": 1
    },
    "stage": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "value": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/valueItem"
      },
      "minItems": 1
    }
  },
  "required": [
    "uuid",
    "info",
    "yAxis",
    "value",
    "description"
  ]
}

=== Bastion-RND/school-lab/specifications/ba575007.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575007-eca0-11ec-8ea0-1337ac062022",
  "description": "Индукция магнитного поля",
  "info": {
    "title": "Индукция магнитного поля",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " Тл",
      "title": "Магнитная индукция",
      "range": {
        "list": [
          {
            "min": -0.175,
            "max": 0.175,
            "precision": 2,
            "factor": "MILLI",
            "calibrationPointsMin": 2
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575021.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575009-eca0-11ec-8ea0-1337ac062022",
  "description": "Измерение силы малых постоянных электрических токов",
  "info": {
    "title": "Гальванометр",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "А",
      "title": "Гальванометр",
      "range": {
        "list": [
          {
            "min": -0.025,
            "max": 0.025,
            "precision": 3,
            "factor": "MICRO",
            "calibrationPointsMin": 2
          },
          {
            "min": -0.01,
            "max": 0.01,
            "precision": 3,
            "factor": "MICRO",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 1
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57501b.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57501a-eca0-11ec-8ea0-1337ac062022",
  "description": "Измеритель ЧД на базе микрофона",
  "info": {
    "title": "Частота дыхания",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "вдох/мин",
      "title": "Частота дыхания",
      "range": {
        "list": [
          {
            "min": 0,
            "max": 100,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "gauge",
        "current",
        "minmax"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575016.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575016-eca0-11ec-8ea0-1337ac062022",
  "description": "Датчик влажности почвы",
  "info": {
    "title": "Влажность почвы",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "%",
      "title": "Влажность",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 100.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575019.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575019-eca0-11ec-8ea0-1337ac062022",
  "description": "Измеритель расстояния",
  "info": {
    "title": "Расстояние",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "м",
      "title": "Расстояние",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 4.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "min": 0.0,
            "max": 2.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 1
      }
    }
  ],
  "value": [
    {
      "title": "Расстояние",
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575c06.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575c06-eca0-11ec-8ea0-1337ac062022",
  "description": "Температура + влажность воздуха",
  "info": {
    "title": "Температура и относительная влажность воздуха",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "°C",
      "title": "Температура",
      "range": {
        "list": [
          {
            "min": -40.0,
            "max": 80.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    },
    {
      "unit": "%",
      "title": "Относительная влажность",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 100.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    },
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 1,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba57501a.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba57501a-eca0-11ec-8ea0-1337ac062022",
  "description": "Устройство подсчета капель на штатив",
  "info": {
    "title": "Счетчик капель",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "кпл",
      "title": "Капли",
      "range": {
        "list": [
          {
            "min": 0,
            "max": 4294967295,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "current"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575012.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575012-eca0-11ec-8ea0-1337ac062022",
  "description": "Электрокардиограмма",
  "info": {
    "title": "Электрокардиограмма",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "В",
      "title": "ЭКГ",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 3.0,
            "precision": 2,
            "factor": "MILLI",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    },
    {
      "unit": "уд/мин",
      "title": "ЧСС",
      "range": {
        "list": [
          {
            "min": 0,
            "max": 300,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
   "stage": [
    "Справочная информация. Приглашение начать измерения.",
    "Процесс измерения",
    "Получение данных",
    "Отображение результатов измерений"
  ],
  "value": [
    {
      "title": "ЭКГ",
      "options": [
        "chart"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    },
    {
      "title": "ЧСС",
      "options": [
        "gauge"
      ],
      "yAxisIndex": 1,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}
