=== Bastion-RND/school-lab/specifications/schema/sensor.schema.json
{
  "$id": "specification.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$definitions": {
    "title": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 1,
      "maxLength": 64
    },
    "rangeListItem": {
      "description": "Range specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "factor": {
          "type": "string",
          "enum": [
            "NORMAL",
            "PICO",
            "NANO",
            "MICRO",
            "MILLI",
            "KILO",
            "MEGA",
            "GIGA",
            "TERA"
          ],
          "default": "NORMAL"
        },
        "precision": {
          "type": "integer",
          "default": 2
        },
        "calibrationPointsMin": {
          "type": "integer",
          "default": 2
        }
      },
      "required": [
        "min",
        "max",
        "factor",
        "precision",
        "calibrationPointsMin"
      ]
    },
    "yAxisItemRange": {
      "description": "YAxis Ranges Specifications",
      "type": "object",
      "properties": {
        "list": {
          "type": "array",
          "items": {
            "$ref": "#/$definitions/rangeListItem"
          },
          "minItems": 1
        },
        "defaultIndex": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        }
      },
      "required": [
        "list",
        "defaultIndex"
      ]
    },
    "yAxisItem": {
      "description": "Single YAxis Specifications",
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "unit": {
          "type": "string",
          "maxLength": 10
        },
        "range": {
          "$ref": "#/$definitions/yAxisItemRange"
        },
        "required": [
          "title",
          "unit",
          "range"
        ]
      }
    },
    "valueItem": {
      "description": "Single Value Specifications",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "yAxisIndex": {
          "type": "integer",
          "default": 0
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "chart",
              "chart2",
              "chart3",
              "chart4",
              "gauge",
              "reference",
              "current",
              "measurements",
              "minmax",
              "bloodPressure",
              "pulse"
            ]
          },
          "minItems": 1,
          "uniqueItems": true,
          "default": [
            "chart",
            "gauge",
            "current",
            "measurements"
          ]
        },
        "errors": {
          "description": "Error Codes with default texts",
          "type": "object"
        }
      },
      "required": [
        "title",
        "options",
        "yAxisIndex",
        "errors"
      ]
    }
  },
  "title": "Sensor specifications",
  "description": "School Laboratory sensor specifications",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "description": {
      "type": "string",
      "maxLength": 64
    },
    "info": {
      "description": "Sensor common information",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$definitions/title"
        },
        "sortOrder": {
          "type": "integer",
          "minimum": -1,
          "default": -1
        }
      },
      "required": [
        "title",
        "sortOrder"
      ]
    },
    "yAxis": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/yAxisItem"
      },
      "minItems": 1
    },
    "stage": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "value": {
      "type": "array",
      "items": {
        "$ref": "#/$definitions/valueItem"
      },
      "minItems": 1
    }
  },
  "required": [
    "uuid",
    "info",
    "yAxis",
    "value",
    "description"
  ]
}

=== Bastion-RND/school-lab/specifications/ba575014.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575014-eca0-11ec-8ea0-1337ac062022",
  "description": "Уровень шума",
  "info": {
    "title": "Шум",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "Па",
      "title": "Шум",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 2.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575025.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575007-eca0-11ec-8ea0-1337ac062022",
  "description": "Датчик магнитного поля Земли {labean™}",
  "info": {
    "title": "Датчик магнитного поля Земли",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " Тл",
      "title": "Магнитное поле Земли",
      "range": {
        "list": [
          {
            "min": -0.175,
            "max": 0.175,
            "precision": 2,
            "factor": "MILLI",
            "calibrationPointsMin": 2
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575023.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575008-eca0-11ec-8ea0-1337ac062022",
  "description": "Окислительно-восстановительный потенциал (Eh)",
  "info": {
    "title": "Окислительно-восстановительный потенциал (Eh)",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "Eh",
      "title": "ОВП",
      "range": {
        "list": [
          {
            "min": -1.0,
            "max":  1.0,
            "precision": 2,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575024.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575005-eca0-11ec-8ea0-1337ac062022",
  "description": "Электрическая проводимость",
  "info": {
    "title": "Концентрация ионов",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "ppm",
      "title": "TDS",
      "range": {
        "list": [
          {
            "title": "1mS = 500ppm",
            "min": 0,
            "max": 12500,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "title": "1mS = 640ppm",
            "min": 0,
            "max": 16000,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "title": "1mS = 700ppm",
            "min": 0,
            "max": 17500,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575003.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575003-eca0-11ec-8ea0-1337ac062022",
  "description": "Относительная влажность воздуха",
  "info": {
    "title": "Относительная влажность воздуха",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "%",
      "title": "Относительная влажность",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 100.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575018.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575018-eca0-11ec-8ea0-1337ac062022",
  "description": "Датчик хлорид-ионов",
  "info": {
    "title": "Хлорид-ионы",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "м/л",
      "title": "Хлорид-ионы",
      "range": {
        "list": [
          {
            "min": 0.00001,
            "max": 1.0,
            "precision": 5,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575004.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575004-eca0-11ec-8ea0-1337ac062022",
  "description": "Освещенность",
  "info": {
    "title": "Уровень освещенности",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": " лк",
      "title": "Освещенность",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 5000.0,
            "precision": 1,
            "factor": "NORMAL",
            "calibrationPointsMin": 2
          },
          {
            "min": 0.0,
            "max": 25000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": 0.0,
            "max": 50000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 0
          },
          {
            "min": 0.0,
            "max": 188000.0,
            "precision": 1,
            "factor": "KILO",
            "calibrationPointsMin": 0
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}

=== Bastion-RND/school-lab/specifications/ba575020.spec.json
{
  "$schema": "schema/sensor.schema.json",
  "uuid": "ba575020-eca0-11ec-8ea0-1337ac062022",
  "description": "Летучие органические вещества",
  "info": {
    "title": "Концентрация ЛОВ",
    "sortOrder": -1
  },
  "yAxis": [
    {
      "unit": "ppb",
      "title": "Летучие органические вещества",
      "range": {
        "list": [
          {
            "min": 0.0,
            "max": 5000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          },
          {
            "min": 0.0,
            "max": 10000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          },
          {
            "min": 0.0,
            "max": 50000.0,
            "precision": 0,
            "factor": "NORMAL",
            "calibrationPointsMin": 1
          }
        ],
        "defaultIndex": 0
      }
    }
  ],
  "value": [
    {
      "title": null,
      "options": [
        "chart",
        "gauge",
        "current",
        "measurements"
      ],
      "yAxisIndex": 0,
      "errors": {
        "0": "Нет ошибки",
        "1": "Датчик не подключен"
      }
    }
  ]
}
