=== Bastion-RND/school-lab/specifications/schema/vendor.schema.json
{
  "$id": "vendor.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Vendor specifications",
  "description": "School Laboratory vendor specifications",
  "type": "object",
  "$defs": {
    "uuid": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36
    },
    "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "vendorLab": {
      "description": "Laboratory of vendor",
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string",
          "minLength": 4,
          "maxLength": 36
        },
        "title": {
          "$ref": "#/$defs/title"
        },
        "description": {
          "$ref": "#/$defs/description"
        },
        "color": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    }
  },
  "properties": {
    "uuid": {
      "$ref": "#/$defs/uuid"
    },
    "title": {
      "$ref": "#/$defs/title"
    },
    "target": {
      "type": "string",
      "description": "This property is needed to service of update"
    },
    "description": {
      "$ref": "#/$defs/description"
    },
    "vendor": {
      "description": "Vendor information",
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$defs/title"
        },
        "description": {
          "$ref": "#/$defs/description"
        },
        "logo": {
          "type": "string"
        },
        "colorPalette": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "title"
      ]
    },
    "labs": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/vendorLab"
          }
        },
        "exclude": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "uuid",
    "target",
    "title",
    "vendor",
    "labs"
  ]
}

=== Bastion-RND/school-lab/specifications/vendor-5ed255d1-8e44-4667-aa39-c61e731ea782.spec.json
{
  "$schema": "schema/vendor.schema.json",
  "uuid": "5ed255d1-8e44-4667-aa39-c61e731ea782",
  "target": "basic",
  "title": "Школьная лаборатория",
  "description": "Школьная лаборатория - программно-аппаратный комплекс, для проведения лабораторных испытаний",
  "vendor": {
    "title": "Бастион",
    "logo": "img/logos/basic/logo.svg"
  },
  "labs": {
    "items": [
      {
        "uuid": "5101"
      },
      {
        "uuid": "5102"
      },
      {
        "uuid": "5103"
      },
      {
        "uuid": "5104"
      },
      {
        "uuid": "51C0"
      },
      {
        "uuid": "51C1"
      },
      {
        "uuid": "51C2"
      }
    ],
    "exclude": ["5104"]
  }
}

=== Bastion-RND/school-lab/specifications/vendor-20c321be-01bf-43d5-8951-a856ad884250.spec.json
{
  "$schema": "schema/vendor.schema.json",
  "uuid": "20c321be-01bf-43d5-8951-a856ad884250",
  "target": "polylab",
  "title": "Полилаб",
  "description": "Полилаб - программно-аппаратный комплекс, для проведения лабораторных испытаний",
  "vendor": {
    "title": "Полимедиа",
    "logo": "img/logos/polylab/logo.svg"
  },
  "labs": {
    "items": [
      {
        "uuid": "5101",
        "color": "#017BC2",
        "title": "Естествознание СШ тип 2"
      },
      {
        "uuid": "5101",
        "color": "#017BC2",
        "title": "Математика"
      },
      {
        "uuid": "5102",
        "color": "#009E96",
        "title": "Естествознание НШ тип 1"
      },
      {
        "uuid": "5102",
        "color": "#009E96",
        "title": "Естествознание СШ тип 1"
      },
      {
        "uuid": "5103",
        "color": "#8BC34A",
        "title": "Естествознание НШ тип 2"
      },
      {
        "uuid": "5103",
        "color": "#8BC34A",
        "title": "География"
      },
      {
        "uuid": "5103",
        "color": "#8BC34A",
        "title": "ОБЖ"
      }
    ],
    "exclude": ["5104", "51C0", "51C1", "51C2"]
  }
}
